name: Repository sync

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
  workflow_dispatch:

jobs:
  prepare:
    if: |
      github.event_name == 'workflow_dispatch' ||
        github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      replacements: ${{ steps.getReplacementsStep.outputs.replacements }}
    steps:
      - uses: rees46/workflow/.github/actions/sync/read-replacements@master
        id: getReplacementsStep
        with:
          appId: ${{ vars.PUBLIVERSIONER_ID }}
          appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
          replacementsRepo: rees46/workflow
          repositoryOwner: rees46
          replacementsPath: github/repo-sync-replacements/skills.yaml

  repoSync:
    needs: prepare
    uses: rees46/workflow/.github/workflows/reusable-repo-sync.yml@master
    secrets:
      appSecret: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
    with:
      appId: ${{ vars.PERSONACLICK_COURIER_ID }}
      replacements: ${{ needs.prepare.outputs.replacements }}
      repositoryOwner: personaclick
      targetRepository: personaclick/skills
      reviewerUsername: ${{ vars.REVIEWER_USERNAME }}
